name = "StabilitySelection"
uuid = "9920510d-a674-4301-82bf-c6690f1e083a"
version = "0.0.1"
authors = ["lancelot-r <lancelotravier@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.7"
DataFrames = "1.8.1"
Distributions = "0.25.122"
GLMNet = "0.7.4"
Random = "1.11.0"
Revise = "3.12.3"
StatsBase = "0.34.8"
julia = "1.10"
